export const INVOICE_LIST_REQUEST = 'INVOICE_LIST_REQUEST';
export const INVOICE_LIST_SUCCESS = 'INVOICE_LIST_SUCCESS';
export const INVOICE_EDIT_SUCCES = "INVOICE_EDIT_SUCCES";
export const INVOICE_CREATE_SUCCESS = 'INVOICE_CREATE_SUCCESS';

